# Generated by Django 5.2.6 on 2025-10-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecepcionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_final', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecepcionApp.equipo')),
            ],
        ),
    ]
