# Generated by Django 5.2.6 on 2025-10-23 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RecepcionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.CharField(max_length=100)),
                ('diagnostico_problema', models.TextField()),
                ('solucion', models.TextField()),
                ('tipo_solucion', models.CharField(max_length=50)),
                ('fecha_diagnostico', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecepcionApp.equipo')),
            ],
        ),
    ]
